services:
  db:
    container_name: integration_testing_container
    image: postgres:15-alpine # Use a specific version
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: testDb
      PGDATA: /var/lib/postgresql/data/pgdata
    command:
      [
        'postgres',
        '-c',
        'fsync=off',
        '-c',
        'full_page_writes=off',
        '-c',
        'synchronous_commit=off',
      ]
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
