services:
  db:
    container_name: integration_testing_container
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: testIntegration
    ports:
      - '5432:5432'
