name: CI/CD Integration Test Pipeline

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Install Docker Compose Plugin
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-compose-plugin

    - name: Ensure Docker COmpose is available
      run: docker compose version

    - name: Run integration test
      run: npm run test:integration
