name: CI/CD Integration Test Pipeline

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js (Alpine)
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'npm'

    - name: Install dependencies
      run: npm install

    - name: Set up Docker with Buildx and Compose
      uses: docker/setup-buildx-action@v2

    - name: Start PostgreSQL Container
      run: |
        # Pull the Alpine-based PostgreSQL image
        docker pull postgres:15-alpine

        # Start PostgreSQL container
        docker run --name integration_testing_container \
          -e POSTGRES_USER=postgres \
          -e POSTGRES_PASSWORD=mysecretpassword \
          -e POSTGRES_DB=testDb \
          -p 5432:5432 \
          -d postgres:15-alpine

        # Wait for PostgreSQL to be ready
        echo "Waiting for PostgreSQL to start..."
        until docker exec integration_testing_container pg_isready; do
          sleep 1
        done
        echo "PostgreSQL is ready!"

    - name: Run Integration Tests
      run: npm run test:integration
